// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://uqgdopxzqmyskuzfloey.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZ2RvcHh6cW15c2t1emZsb2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNjI3NjcsImV4cCI6MjA0ODgzODc2N30.huEsyvAaEHZ94R8ntjUsDGaopNi-VpUy07PD0eOLwbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);